CREATE DATABASE IF NOT EXISTS tienda;
USE tienda;

CREATE TABLE CLIENTE(
  DNI VARCHAR(9) NOT NULL COMMENT 'DNI DEL CLIENTE',
  Nombre VARCHAR(30) NOT NULL COMMENT 'NOMBRE DEL CLIENTE',
  Apellidos VARCHAR(255) NOT NULL,
  Fecha_Nac DATE,
  Direccion VARCHAR(255) NOT NULL,
  Cod_Postal VARCHAR(6),
  CONSTRAINT PK_CLIENTE
    PRIMARY KEY(DNI)
);

CREATE TABLE VISITA(
  DNI_Cli VARCHAR(9) NOT NULL COMMENT 'DNI DEL CLIENTE',
  DNI_Comercial VARCHAR(9) NOT NULL COMMENT 'DNI DEL COMERCIAL',
  Fecha_Visita DATE,
  CONSTRAINT PK_VISITA
    PRIMARY KEY(DNI_Cli, DNI_Comercial, Fecha_Visita)
);

CREATE TABLE ARTICULO(
  Cod_Art VARCHAR(7) NOT NULL COMMENT 'CODIGO DE ARTICULO',
  Descripcion TEXT COMMENT 'DESCRIPCION DEL ARTICULO',
  Precio int(9) NOT NULL,
  Stock int(9) DEFAULT 100,
  CONSTRAINT PK_ARTICULO
    PRIMARY KEY(Cod_Art)
);


CREATE TABLE COMERCIAL(
  DNI VARCHAR(9) NOT NULL COMMENT 'DNI DEL COMERCIAL',
  Nombre VARCHAR(50) NOT NULL COMMENT 'NOMBRE DEL COMERCIAL',
  Apellidos VARCHAR(255) NOT NULL,
  Fecha_Nac DATE,
  Direccion VARCHAR(255) NOT NULL,
  Cod_Postal VARCHAR(5) NOT NULL,
  CONSTRAINT PK_COMERCIAL
    PRIMARY KEY(DNI)
);

CREATE TABLE FACTURA(
  Cod_Fac VARCHAR(6) COMMENT 'Codigo de factura',
  DNI VARCHAR(9) NOT NULL,
  Fecha_Fac DATE,
  Importe int(20) NOT NULL COMMENT 'Importe de la factura',
  CONSTRAINT PK_FACTURA
    PRIMARY KEY (Cod_Fac),
  CONSTRAINT FK_CLIENTE_FACTURA
    FOREIGN KEY(DNI)
    REFERENCES CLIENTE(DNI)
);

CREATE TABLE  ALBARAN(
  Cod_Alb VARCHAR(6) NOT NULL COMMENT 'Codigo de albaran',
  Cod_Fac VARCHAR(6) NOT NULL COMMENT 'Codigo de factura',
  Fecha_Alb DATE,
  Cod_Art VARCHAR(7) NOT NULL,
  Cantidad int(5) NOT NULL,
  CONSTRAINT PK_ALBARAN
    PRIMARY KEY(Cod_Alb),
  CONSTRAINT FK_FACTURA_ALBARAN
    FOREIGN KEY(Cod_Fac)
    REFERENCES FACTURA(Cod_Fac),
  CONSTRAINT FK_ARTICULO_ALBARAN
    FOREIGN KEY(Cod_Art)
    REFERENCES ARTICULO(Cod_Art)
);
